/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stm32f4xxGPIO.h>
#include "stm32f4xxSPI.h"
#include <string.h>
#include <stm32f4xxI2c.h>

/*
 * I2C2-> PB10 - SCL, PB11 - SDA
 */

void delay(void);

int main(void)
{

	GPIOB_PCEN();
	I2C1_PCEN();

	GPIO_INIT(GPIOB,10,AF_Mode,OpenDrain,highSpeed,pullUp);
	GPIO_AFMODE(GPIOB,10,AF4);
	GPIO_INIT(GPIOB,11,AF_Mode,OpenDrain,highSpeed,pullUp);
	GPIO_AFMODE(GPIOB,11,AF4);

	I2C_Config_t i2c;

	i2c.FastOrStandardMode = standardMode;
	i2c.SCL_freq = 100000;
	i2c.I2Cx = I2C1;
	i2c.clockStretch = 1;

	I2C_INIT(i2c);

	I2C_PE(i2c.I2Cx,enable);

	uint8_t *msg =0;

	while(1){


		I2C_Write(i2c.I2Cx,msg,0x88);
		msg++;

	}
}

void delay(void){
	for(int i=0; i<50000;i++);
}
